import regalo1 from "../../../assets/fakeimages/regalo1.png";
import regalo2 from "../../../assets/fakeimages/regalo2.png";
import regalo3 from "../../../assets/fakeimages/regalo3.png";
import regalo4 from "../../../assets/fakeimages/regalo4.png";
import marca1 from "../../../assets/fakeimages/marca1.png";
import marca2 from "../../../assets/fakeimages/marca2.png";
import marca3 from "../../../assets/fakeimages/marca3.png";
export const regalos = [
  {
    id: "asdasd1",
    img: marca2,
    store: "SALUD",
    storeType: "Farmacia",
    balance: "c$500",
    minAmount: "A partir de $5000",
    type: "classic",
    usage: [
      "Los c$500 que te regalamos equivalen a $500.",
      "Los podes usar en compras de $2500 o más.",
      "Tocá el botón 'USAR MIS CRONIPESOS' y copiá el regalo.",
      "Ingresá en el botón 'Ir a ARCOR' y pegá tu regalo para habilitar los cronipe$os que usaste.",
      "Los podés usar en todos lo productos de la web.",
    ],
  },
  {
    id: "asdasd2",
    img: marca2,
    store: "SALUD",
    storeType: "Farmacia",
    balance: "c$100",
    minAmount: "A partir de $2000",
    type: "classic",
    usage: [
      "Los c$500 que te regalamos equivalen a $500.",
      "Los podes usar en compras de $2500 o más.",
      "Tocá el botón 'USAR MIS CRONIPESOS' y copiá el regalo.",
      "Ingresá en el botón 'Ir a ARCOR' y pegá tu regalo para habilitar los cronipe$os que usaste.",
      "Los podés usar en todos lo productos de la web.",
    ],
  },
  {
    id: "asdasd3",
    img: marca1,
    store: "ARCOR",
    storeType: "Mercado",
    balance: "c$1500",
    minAmount: "A partir de $4500",
    type: "black",
    usage: [
      "Los c$500 que te regalamos equivalen a $500.",
      "Los podes usar en compras de $2500 o más.",
      "Tocá el botón 'USAR MIS CRONIPESOS' y copiá el regalo.",
      "Ingresá en el botón 'Ir a ARCOR' y pegá tu regalo para habilitar los cronipe$os que usaste.",
      "Los podés usar en todos lo productos de la web.",
    ],
  },
  {
    id: "asdasd4",
    img: marca1,
    store: "ARCOR",
    storeType: "Mercado",
    balance: "c$500",
    minAmount: "A partir de $5000",
    type: "classic",
    usage: [
      "Los c$500 que te regalamos equivalen a $500.",
      "Los podes usar en compras de $2500 o más.",
      "Tocá el botón 'USAR MIS CRONIPESOS' y copiá el regalo.",
      "Ingresá en el botón 'Ir a ARCOR' y pegá tu regalo para habilitar los cronipe$os que usaste.",
      "Los podés usar en todos lo productos de la web.",
    ],
  },
  {
    id: "asdasd5",
    img: marca3,
    store: "CINEMA",
    storeType: "Cine",
    balance: "c$500",
    minAmount: "A partir de $5000",
    type: "black",
    usage: [
      "Los c$500 que te regalamos equivalen a $500.",
      "Los podes usar en compras de $2500 o más.",
      "Tocá el botón 'USAR MIS CRONIPESOS' y copiá el regalo.",
      "Ingresá en el botón 'Ir a ARCOR' y pegá tu regalo para habilitar los cronipe$os que usaste.",
      "Los podés usar en todos lo productos de la web.",
    ],
  },
  {
    id: "asdasd6",
    img: marca2,
    store: "SALUD",
    storeType: "Farmacia",
    balance: "c$100",
    minAmount: "A partir de $2000",
    type: "classic",
    usage: [
      "Los c$100 que te regalamos equivalen a $100.",
      "Los podes usar en compras de $2500 o más.",
      "Tocá el botón 'USAR MIS CRONIPESOS' y copiá el regalo.",
      "Ingresá en el botón 'Ir a ARCOR' y pegá tu regalo para habilitar los cronipe$os que usaste.",
      "Los podés usar en todos lo productos de la web.",
    ],
  },
  {
    id: "asdasd7",
    img: regalo3,
    store: "Pepsi",
    storeType: "Gaseosas",
    balance: "c$700",
    minAmount: "A partir de $7000",
    type: "classic",
    usage: [
      "Los c$700 que te regalamos equivalen a $700.",
      "Los podes usar en compras de $2500 o más.",
      "Tocá el botón 'USAR MIS CRONIPESOS' y copiá el regalo.",
      "Ingresá en el botón 'Ir a ARCOR' y pegá tu regalo para habilitar los cronipe$os que usaste.",
      "Los podés usar en todos lo productos de la web.",
    ],
  },
  {
    id: "asdasd8",
    img: regalo4,
    store: "Terrabusi",
    storeType: "Galletitas",
    balance: "c$500",
    minAmount: "A partir de $5000",
    type: "classic",
    usage: [
      "Los c$5000 que te regalamos equivalen a $5000.",
      "Los podes usar en compras de $7500 o más.",
      "Tocá el botón 'USAR MIS CRONIPESOS' y copiá el regalo.",
      "Ingresá en el botón 'Ir a ARCOR' y pegá tu regalo para habilitar los cronipe$os que usaste.",
      "Los podés usar en todos lo productos de la web.",
    ],
  },
];
